# Generated by Django 4.2.7 on 2023-11-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=10)),
                ('precio_distribuidor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='productos')),
            ],
        ),
    ]
