# Generated by Django 4.2.7 on 2023-11-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caja',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('SOL', 'Sol peruano')], default='USD', max_length=10),
        ),
    ]
