# Generated by Django 4.2.7 on 2023-11-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_caja_producto_en_oferta_producto_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto',
            field=models.CharField(default='Producto predeterminado', max_length=100),
        ),
    ]
