# Generated by Django 4.2.7 on 2023-11-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(default='CAJAS x 2 M2', max_length=100),
        ),
    ]
