# Generated by Django 4.2.7 on 2023-11-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_instalada',
            field=models.ImageField(default='images/default.jpg', upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='images/default.jpg', upload_to='productos'),
        ),
    ]
