# Generated by Django 4.2.7 on 2023-11-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_producto_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='SIN CATEGORIA', max_length=100),
        ),
    ]
